version: '3.8'
services:
  app:
    build: .
    container_name: shrinkr-app
    ports: 
      - 3000:3000
    depends_on:
      - prometheus
      - redis
    environment:
      - NODE_ENV=production
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3002:3000
    depends_on:
      - prometheus

  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - 6379:6379
    

